name: ado-github-pipeline

trigger: none

pool:
  name: vikas007-agent

jobs:
- job: Terraform_Job
  displayName: "Terraform Job"

  steps:

  - checkout: self

  - task: TerraformInstaller@1
    displayName: "Install Terraform"
    inputs:
      terraformVersion: '1.13.2'

  - task: TerraformTask@5
    displayName: "Terraform Init"
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(Build.SourcesDirectory)/140726_child_parrant_project/env_parrant'
      backendServiceArm: 'adopipeline-app-reg'
      backendAzureRmOverrideSubscriptionID: '09313c5c-930a-453c-a90c-32ef23577e6b'
      backendAzureRmResourceGroupName: 'b18g35-common-rg'
      backendAzureRmStorageAccountName: 'b18g35storageaccount'
      backendAzureRmContainerName: 'vikasado'
      backendAzureRmKey: 'vikas_ado.tfstate'

  - task: TerraformTask@5
    displayName: "Terraform Validate"
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(Build.SourcesDirectory)/140726_child_parrant_project/env_parrant'

  - task: TerraformTask@5
    displayName: "Terraform Plan"
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(Build.SourcesDirectory)/140726_child_parrant_project/env_parrant'
      environmentServiceNameAzureRM: 'adopipeline-app-reg'
      environmentAzureRmOverrideSubscriptionID: '09313c5c-930a-453c-a90c-32ef23577e6b'

  - task: TerraformTask@5
    displayName: "Terraform Apply"
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(Build.SourcesDirectory)/140726_child_parrant_project/env_parrant'
      commandOptions: '-auto-approve'
      environmentServiceNameAzureRM: 'adopipeline-app-reg'
      environmentAzureRmOverrideSubscriptionID: '09313c5c-930a-453c-a90c-32ef23577e6b'